/*
 * Copyright 2015 Joseph Landry All Rights Reserved
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "tokens.h"
#include "escstr.h"

char *PPTOKEN_STRINGS[PPTN_NTOKENS] = {
	"PPTN_EOF",
	"PPTN_HEADERNAME",
	"PPTN_IDENTIFIER",
	"PPTN_PPNUMBER",
	"PPTN_CHARACTERCONSTANT",
	"PPTN_STRINGLITERAL",
	"PPTN_IF",
	"PPTN_IFDEF",
	"PPTN_IFNDEF",
	"PPTN_ELIF",
	"PPTN_ELSE",
	"PPTN_ENDIF",
	"PPTN_INCLUDE",
	"PPTN_DEFINE",
	"PPTN_LINE",
	"PPTN_ERROR",
	"PPTN_PRAGMA",
	"PPTN_WHITESPACE",
	"PPTN_NEWLINE",
	"PPTN_NE_OP",
	"PPTN_EXLAMATIONMARK",
	"PPTN_GLUE_OP",
	"PPTN_HASH",
	"PPTN_AND_OP",
	"PPTN_AND_ASSIGN",
	"PPTN_AMPERSAND",
	"PPTN_MOD_ASSIGN",
	"PPTN_PERCENT",
	"PPTN_LPAREN",
	"PPTN_RPAREN",
	"PPTN_MUL_ASSIGN",
	"PPTN_ASTERISK",
	"PPTN_INC_OP",
	"PPTN_ADD_ASSIGN",
	"PPTN_PLUS_SIGN",
	"PPTN_COMMA",
	"PPTN_DEC_OP",
	"PPTN_SUB_ASSIGN",
	"PPTN_PTR_OP",
	"PPTN_MINUS_SIGN",
	"PPTN_ELLIPSIS",
	"PPTN_PERIOD",
	"PPTN_DIV_ASSIGN",
	"PPTN_SLASH",
	"PPTN_COLON",
	"PPTN_SEMICOLON",
	"PPTN_SL_ASSIGN",
	"PPTN_SL_OP",
	"PPTN_LE_OP",
	"PPTN_LCHEVRON",
	"PPTN_EQ_OP",
	"PPTN_EQUAL",
	"PPTN_SR_ASSIGN",
	"PPTN_SR_OP",
	"PPTN_GE_OP",
	"PPTN_RCHEVRON",
	"PPTN_QUESTION_MARK",
	"PPTN_LBRACKET",
	"PPTN_RBRACKET",
	"PPTN_XOR_ASSIGN",
	"PPTN_CIRCUMFLEX",
	"PPTN_LBRACE",
	"PPTN_OR_ASSIGN",
	"PPTN_OR_OP",
	"PPTN_PIPE",
	"PPTN_RBRACE",
	"PPTN_TILDE",
};

void printPPToken(struct pptoken pptoken){
	printf("[lexeme:\"");
	puts_escaped(pptoken.lexeme, pptoken.lexeme + strlen(pptoken.lexeme));
	printf("\", name:%s]\n", PPTOKEN_STRINGS[pptoken.name]);
}
